#ifndef ISYSVERSION_H
#define ISYSVERSION_H

#define ISYS_PRODUCT_ID_NUMBER       0           //<PRODUCT_ID_NUMBER>
#define ISYS_PRODUCT_VERSION_NUMBER  0           //<PRODUCT_VERSION_NUMBER>
#define ISYS_PRODUCT_REVISION_NUMBER 0           //<PRODUCT_REVISION_NUMBER>
#define ISYS_PRODUCT_TEST_NUMBER     70           //<PRODUCT_TEST_NUMBER>

#endif

