#ifndef DUCOLIBVERSION_H
#define DUCOLIBVERSION_H

#define PRODUCT_ID_NUMBER       13020       //<PRODUCT_ID_NUMBER>
#define PRODUCT_VERSION_NUMBER  9           //<PRODUCT_VERSION_NUMBER>
#define PRODUCT_REVISION_NUMBER 0           //<PRODUCT_REVISION_NUMBER>
#define PRODUCT_TEST_NUMBER     0           //<PRODUCT_TEST_NUMBER>

#endif

