#ifndef SYSVERSION_H
#define SYSVERSION_H

#define SYS_PRODUCT_ID_NUMBER       17          //<PRODUCT_ID_NUMBER>
#define SYS_PRODUCT_VERSION_NUMBER  8           //<PRODUCT_VERSION_NUMBER>
#define SYS_PRODUCT_REVISION_NUMBER 3           //<PRODUCT_REVISION_NUMBER>
#define SYS_PRODUCT_TEST_NUMBER     0           //<PRODUCT_TEST_NUMBER>

#endif

