#ifndef STDVERSION_H
#define STDVERSION_H

#define STD_PRODUCT_ID_NUMBER       304         //<PRODUCT_ID_NUMBER>
#define STD_PRODUCT_VERSION_NUMBER  7           //<PRODUCT_VERSION_NUMBER>
#define STD_PRODUCT_REVISION_NUMBER 1           //<PRODUCT_REVISION_NUMBER>
#define STD_PRODUCT_TEST_NUMBER     0           //<PRODUCT_TEST_NUMBER>

#endif

