#ifndef APPVERSION_H
#define APPVERSION_H

#define PRODUCT_ID_NUMBER       17012       //<PRODUCT_ID_NUMBER>
#define PRODUCT_VERSION_NUMBER  0           //<PRODUCT_VERSION_NUMBER>
#define PRODUCT_REVISION_NUMBER 0           //<PRODUCT_REVISION_NUMBER>
#define PRODUCT_TEST_NUMBER     8           //<PRODUCT_TEST_NUMBER>

#endif

