#ifndef DRVVERSION_H
#define DRVVERSION_H

#define DRV_PRODUCT_ID_NUMBER       303         //<PRODUCT_ID_NUMBER>
#define DRV_PRODUCT_VERSION_NUMBER  6           //<PRODUCT_VERSION_NUMBER>
#define DRV_PRODUCT_REVISION_NUMBER 3           //<PRODUCT_REVISION_NUMBER>
#define DRV_PRODUCT_TEST_NUMBER     0           //<PRODUCT_TEST_NUMBER>

#endif

