#ifndef STDCOMMVERSION_H
#define STDCOMMVERSION_H

#define STD_PRODUCT_ID_NUMBER       305         //<PRODUCT_ID_NUMBER>
#define STD_PRODUCT_VERSION_NUMBER  9           //<PRODUCT_VERSION_NUMBER>
#define STD_PRODUCT_REVISION_NUMBER 6           //<PRODUCT_REVISION_NUMBER>
#define STD_PRODUCT_TEST_NUMBER     0           //<PRODUCT_TEST_NUMBER>

#endif

